// node/properties/people/PeopleFilterOptions.ts
export const peopleFilterOptions = [
    { name: 'Accounting Administrator', value: 'accounting_administrator' },
    { name: 'Anniversary', value: 'anniversary' },
    { name: 'Birthdate', value: 'birthdate' },
    { name: 'Child', value: 'child' },
    { name: 'Created At', value: 'created_at' },
    { name: 'First Name', value: 'first_name' },
    { name: 'Gender', value: 'gender' },
    { name: 'Given Name', value: 'given_name' },
    { name: 'Grade', value: 'grade' },
    { name: 'Graduation Year', value: 'graduation_year' },
    { name: 'ID', value: 'id' },
    { name: 'Inactivated At', value: 'inactivated_at' },
    { name: 'Last Name', value: 'last_name' },
    { name: 'Medical Notes', value: 'medical_notes' },
    { name: 'Membership', value: 'membership' },
    { name: 'MFA Configured', value: 'mfa_configured' },
    { name: 'Middle Name', value: 'middle_name' },
    { name: 'Nickname', value: 'nickname' },
    { name: 'Passed Background Check', value: 'passed_background_check' },
    { name: 'People Permissions', value: 'people_permissions' },
    { name: 'Primary Campus ID', value: 'primary_campus_id' },
    { name: 'Remote ID', value: 'remote_id' },
    { name: 'Search Name', value: 'search_name' },
    { name: 'Search Name Or Email', value: 'search_name_or_email' },
    { name: 'Search Name Or Email Or Phone Number', value: 'search_name_or_email_or_phone_number' },
    { name: 'Search Phone Number', value: 'search_phone_number' },
    { name: 'Search Phone Number E164', value: 'search_phone_number_e164' },
    { name: 'Site Administrator', value: 'site_administrator' },
    { name: 'Status', value: 'status' },
    { name: 'Updated At', value: 'updated_at' },
];
